name: Auto Close Non-main PRs

on:
  pull_request_target:
    branches-ignore:
      - main

jobs:
  close-pr-if-not-main:
    runs-on: ubuntu-latest
    
    steps:
      - name: Close PRs
        uses: actions/github-script@v7
        with:
          script: |
            const baseBranch = context.payload.pull_request.base.ref;
            console.log(`Base branch: ${baseBranch}`);

            const prNumber = context.payload.pull_request.number;
            await github.rest.issues.createComment({
              issue_number: prNumber,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "This pull request cannot be merged because the base branch is not `main`. Please change the base branch to `main`."
            });

            await github.rest.pulls.update({
              pull_number: prNumber,
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'closed'
            });