name: Web page to Markdown
on:
  issues:
    types:
      - opened
jobs:
  WebPageToMarkdown:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: write
    steps:
      - name: Issue does not need to generate markdown
        if: ${{ !startsWith(github.event.issue.title, '[Auto]') }}
        shell: bash
        run: echo "This issue does not need to generate a markdown file." 1>&2; exit 1;
      - name: The description of the issue is empty
        if: ${{ !github.event.issue.body }}
        shell: bash
        run: echo "The description of the issue is empty." 1>&2; exit 1;

      - uses: actions/checkout@v3
      - name: Crawl pages and generate Markdown files
        uses: budblack/article-webpage-to-markdown-action@dev
        with:
          newsLink: '${{ github.event.issue.Body }}'
          includeSelector: '.post-content'
          ignoreSelector: '.ad-wrapper'
          markDownFilePath: './articles/_raw/'
          githubToken: ${{ github.token }}

      - name: article-markdown-auto-translat
        uses: budblack/article-markdown-auto-translate@dev
        with:
          issueTitle: '${{ github.event.issue.title }}'
          newsLink: '${{ github.event.issue.Body }}'
          ignoreSelector: '.ad-wrapper'
          markDownFilePath: './articles/_raw/'
          githubToken: ${{ github.token }}
          openaiApiKey: ${{ secrets.OPENAI_API_KEY }}

      - name: Pull latest changes
        run: git pull origin main

      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: '${{ github.event.issue.title }}'
          file_pattern: articles/**/*.md
          commit_user_name: PageToMarkdown Bot
          commit_user_email: PageToMarkdown-bot@freeCodeCamp.org
